function CFKADS255820240419042427ZDataLogUserSync = importpicarro(filename, dataLines)
%IMPORTFILE Import data from a text file
%  CFKADS255820240419042427ZDATALOGUSERSYNC = IMPORTFILE(FILENAME) reads
%  data from text file FILENAME for the default selection.  Returns the
%  data as a table.
%
%  CFKADS255820240419042427ZDATALOGUSERSYNC = IMPORTFILE(FILE,
%  DATALINES) reads data for the specified row interval(s) of text file
%  FILENAME. Specify DATALINES as a positive scalar integer or a N-by-2
%  array of positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  CFKADS255820240419042427ZDataLogUserSync = importfile("C:\Users\Lincoln Scheer\Desktop\5-7-2024-Dataset\picarro\2024\04\19\CFKADS2558-20240419-042427Z-DataLog_User_Sync.dat", [1, 1]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 07-May-2024 14:02:32

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, 1];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 21);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["DATE", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21"];
opts.SelectedVariableNames = "DATE";
opts.VariableTypes = ["datetime", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "DATE", "InputFormat", "yyyy-MM-dd");

% Import the data
CFKADS255820240419042427ZDataLogUserSync = readtable(filename, opts);

end